
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:credit_aplication
    username: daniel
    password:
  jpa:
     show-sql: true
     properties:
       hibernate:
         format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

